
List doctorList = [
  {

    "Dr.Sandeep Patel",
    "Density",
    "ABC Hospital-1, Ahmedabad",
    250,
    4.5,
    79.2,
    "/assets/dr.jpg",
    "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "DR. Ashok Seth",
    "category": "density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":"ABC Hospital-2, Anand",
    "image":"assets/doctor.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Deepak Agrawal",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" ABC Hospital-3, Vadodara",
    "image":"assets/teeth.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Rohan Patir",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 250.0,
    "location":" ABC Hospital-1, Ahmedabad",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {

    "name": "Dr. Ajay Kaul",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" ABC Hospital-3, Vadodara",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Nveen Mishra",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" ABC Hospital-2, Anand",
    "image": "assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name":"Dr. Suresh Advani",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" ABC Hospital-1, Ahmedabad",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name":"Dr. Manjindar Singh",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 250.0,
    "location":" ABC Hospital-2, Anand",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name":"Dr. Kapil Kumar",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 350.0,
    "location":" ABC Hospital-3, Vadodara",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
///////NEUROLOGY
  {
    "name": "Dr. Vijay Dikshit",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 600.0,
    "location":" ABC Hospital-1, Ahmedabad",
    "image":"assets/Neurology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Krishna S Iyer",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 800.0,
    "location":" ABC Hospital-3, Vadodara",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Sujit Chaudhry",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location":" ABC Hospital-2, Anand",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Nikhil Kumar",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location":" ABC Hospital-1, Ahmedabad",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Vinod Raina",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" ABC Hospital-2, Anand",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
///////////Orthopedics

  {
    "name": "Dr. Nandkishor Kapadia ",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" ABC Hospital-3, Vadodara",
    "image":"assets/Neurology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Kishor Saxena",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" ABC Hospital-2, Anand",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Pradeep Sharma",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":"ABC Hospital-3, Vadodara",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. EC Vinay Kumar",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":"ABC Hospital-1, Ahmedabad",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Rahul Bhargava",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": "ABC Hospital-2, Anand",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
///////cardiology and vascular disease

  {
    "name": "Dr. P.L Dhingra",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": " ABC Hospital-1, Ahmedabad",
    "image":"assets/cardiology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. Pawan Rawal",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": " ABC Hospital-2, Anand",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name":"Dr. Sanjay Govil",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location": "ABC Hospital-3, Vadodara",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name":"Dr. Sunil Kumar",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 350.0,
    "location": " ABC Hospital-2, Anand",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
];

